all:
	clang++ -mno-red-zone -std=c++17 -g main.cpp -o main

unoptimized:
	clang++ -mno-red-zone -std=c++17 -g main.cpp -o main

default:
	clang++ -std=c++17 -g main.cpp -o main

clean:
	rm -rf main *.dSYM *.s
