all:
# 	clang++ -std=c++17 -g -O0 main.cpp -o main && ./main
	clang++ -std=c++17 -g -O3 main.cpp -o main && ./main

debug:
# 	clang++ -std=c++17 -g -O0 main.cpp -o main && lldb ./main
	clang++ -std=c++17 -g -O3 main.cpp -o main && lldb ./main

run:
	./main
# 	clang++ -std=c++17 -g -O0 main.cpp -o main && ./main

clean:
	rm -rf main *.dSYM *.s
