# ===
# Compile and link main.cpp in a single step
# ===

# -o filename = “put the output in this file”, whether it’s an
# executable or an object file — depending on if you used -c.
main:
	clang++ main.cpp -o main

# Clean all files from directory.
clean:
	rm -f main
