main: 01-cout 02-cin-bool 03-cin-string

01-cout: 01-cout.cpp
	clang++ 01-cout.cpp -o 01-cout

02-cin-bool: 02-cin-bool.cpp
	clang++ 02-cin-bool.cpp -o 02-cin-bool

03-cin-string: 03-cin-string.cpp
	clang++ 03-cin-string.cpp -o 03-cin-string

clean:
	rm -f 01-cout 02-cin-bool 03-cin-string
